window.app = (function () {
  'use strict';

  var modules = {};

  function app(first, second) {
    if ($.type(first) === 'function') {
      first(app);
    } else if ($.type(first) === 'string' && $.type(second) === 'function') {
      modules[first] = second(app);
    }
  }

  app.el = $('#app');

  app.tpl = function (name) {
    // defined in src/templates.js, generated by grunt job
    return window.templates[name];
  };

  app.get = function (name) {
    return modules[name];
  };

  return $.observable(app);

}());
