window.app = (function (window) {
    'use strict';

    var app = $.observable(function (fn) {
        fn(app);
    });

    app.el = $('#app');
    app.tpl = function (name) {
        // defined in src/templates.js, generated by grunt job
        return window.templates[name];
    };

    return app;

}(window));